;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        forward-sexp
        guile-insert-closing
        indent-for-tab-command
        insert-pair
        insert-parentheses
        insert-square-brackets
        kill-region
        rectangle-mark-mode
        ))

(setq mc/cmds-to-run-once
      '(
        ))
